name: Run

on:
  push:
    path: "*"

  workflow_dispatch:

jobs:
  Start:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Checkout
      uses: actions/checkout@main

    - name: Run Command
      run: |
        WGET_HEADER="User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0"
        curl https://apkcombo.com
        curl https://apkcombo.com

    - name: Delete Workflow Runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 0
